servers

diff --git a/dockerfile/hooks/check b/dockerfile/hooks/check
--- a/dockerfile/hooks/check
+++ b/dockerfile/hooks/check
@@ -16,19 +16,20 @@
 # limitations under the License.
 #
 echo "------ dolphinscheduler check - server - status -------"
-sleep 10
-for i in `seq 30`
-do
-    server_num=`cat /tmp/logs/* | grep -E "worker start fetch tasks|Started MasterServer in|Started ApiApplicationServer in|alert server ready start" | wc -l`
-    if [ $server_num -eq 4 ]
-    then
-        echo "Server all start successfully"
-        exit 0
-    else
-        echo "loop $i"
-        sleep 3
-    fi
-done
-echo "Server start failed $server_num"
-cat /tmp/logs/* | grep -E "worker start fetch tasks|Started MasterServer in|Started ApiApplicationServer in|alert server ready start"
-exit 255
+sleep 60
+server_num=$(docker top `docker container list | grep '/sbin/tini' | awk '{print $1}'`| grep java | grep "dolphinscheduler" | awk -F 'classpath ' '{print $2}' | awk '{print $2}' | sort | uniq -c | wc -l)
+if [ $server_num -eq 5 ]
+then
+    echo "Server all start successfully"
+else
+    echo "Server start failed "$server_num
+    exit 1
+fi
+ok=`curl http://127.0.0.1:8888/dolphinscheduler/login -d 'userName=admin&userPassword=dolphinscheduler123' -v | grep "login success" | wc -l`
+if [ $server_num -eq 1 ]
+then
+    echo "Servers is ready"
+else
+    echo "Servers is not ready"
+    exit 1
+fi
