improve ci

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -44,16 +44,17 @@ jobs:
     outputs:
       not-ignore: ${{ steps.filter.outputs.not-ignore }}
     steps:
+      - uses: actions/checkout@v2
       - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
         id: filter
         with:
           filters: |
             not-ignore:
-              - '!(docs/**)!(dolphinscheduler-ui/**)!(dolphinscheduler-ui-next/**)!(docs/**)'
+              - '!(docs/**)'
   build:
     name: Backend-Build
     needs: paths-filter
-    if: ${{ needs.paths-filter.outputs.not-ignore == 'true' }}
+    if: ${{ (needs.paths-filter.outputs.not-ignore == 'true') || (github.event_name == 'push') }}
     runs-on: ubuntu-latest
     timeout-minutes: 30
     steps:
@@ -86,6 +87,10 @@ jobs:
     steps:
       - name: Status
         run: |
+          if [[ ${{ github.event_name }} == 'push' && ${{ needs.build.result }} != 'success' ]]; then
+            echo "Build Failed!"
+            exit -1
+          fi
           if [[ ${{ needs.paths-filter.outputs.not-ignore }} == 'false' ]]; then
             echo "Skip Build!"
             exit 0
diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -35,6 +35,7 @@ jobs:
     outputs:
       not-ignore: ${{ steps.filter.outputs.not-ignore }}
     steps:
+      - uses: actions/checkout@v2
       - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
         id: filter
         with:
@@ -44,7 +45,7 @@ jobs:
   build:
     name: E2E-Build
     needs: paths-filter
-    if: ${{ needs.paths-filter.outputs.not-ignore == 'true' }}
+    if: ${{ (needs.paths-filter.outputs.not-ignore == 'true') || (github.event_name == 'push') }}
     runs-on: ubuntu-latest
     timeout-minutes: 20
     steps:
@@ -160,6 +161,10 @@ jobs:
     steps:
       - name: Status
         run: |
+          if [[ ${{ github.event_name }} == 'push' && ${{ needs.e2e.result }} != 'success' ]]; then
+            echo "E2E Failed!"
+            exit -1
+          fi
           if [[ ${{ needs.paths-filter.outputs.not-ignore }} == 'false' ]]; then
             echo "Skip E2E!"
             exit 0
diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -42,6 +42,7 @@ jobs:
     outputs:
       not-ignore: ${{ steps.filter.outputs.not-ignore }}
     steps:
+      - uses: actions/checkout@v2
       - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
         id: filter
         with:
@@ -51,7 +52,7 @@ jobs:
   unit-test:
     name: Unit-Test
     needs: paths-filter
-    if: ${{ needs.paths-filter.outputs.not-ignore == 'true' }}
+    if: ${{ (needs.paths-filter.outputs.not-ignore == 'true') || (github.event_name == 'push') }}
     runs-on: ubuntu-latest
     timeout-minutes: 30
     steps:
@@ -119,6 +120,10 @@ jobs:
     steps:
       - name: Status
         run: |
+          if [[ ${{ github.event_name }} == 'push' && ${{ needs.unit-test.result }} != 'success' ]]; then
+          echo "Unit Test Failed!"
+          exit -1
+          fi
           if [[ ${{ needs.paths-filter.outputs.not-ignore }} == 'false' ]]; then
             echo "Skip Unit Test!"
             exit 0
